version: '3'

services:
    mongodb:
        image: "mongo:3.5.13"
        volumes:
            - ./db:/data/db
        ports:
            - "27017:27017"
        networks:
            - default
    city-service:
        image: worker-01:5000/city-service
        environment:
            - FLASK_ENV=DEV
        build: .
        networks:
            - default

networks:
  default:
    external:
        name: ticketing_default
